# This packages all of the api into one file for on the go... stuff

outputfile=liborange-pocket.nut
tempoutputfile=$outputfile"-temp"
apifile="orange_api_util.nut"
filedir="orange-api"

cd $filedir

if [ -r $outputfile ]; then
	rm $outputfile
fi

echo "//" $apifile > $tempoutputfile
cat $apifile>>$tempoutputfile

for file in `ls`; do
	if [ "${file: -4}" == ".nut" ] && [ "$file" != $tempoutputfile ] && [ "$file" != $apifile ]; then
		echo "" >> $tempoutputfile
		echo "" >> $tempoutputfile
		echo "//" $file >> $tempoutputfile;
		cat $file>>$tempoutputfile
	fi
done

echo "" >> $tempoutputfile
echo "" >> $tempoutputfile

cd ..

echo "// auto generated by singlescript.sh" > $outputfile
echo "// this is the entire orange library condensed into one script" >> $outputfile
echo "" >> $outputfile
while read -r line; do
	if [ "$line" != 'import("orange-api/orange_api_util.nut")' ] && [ "$line" != '${THEFILE//import("orange-api/orange_api_util.nut")}' ]; then
		echo "$line" >> $outputfile;
	fi
done < $filedir"/"$tempoutputfile


cd $filedir
rm $tempoutputfile